"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path

# ==============================
# BASE
# ==============================

BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================
# SEGURIDAD
# ==============================

SECRET_KEY = 'django-insecure-ap$bd&xtk-!cum&t=jchr@8g26!9&tokptphbn5^os46rt&iko'

DEBUG = True

ALLOWED_HOSTS = ['*']


# ==============================
# APLICACIONES
# ==============================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'users',
]


# ==============================
# MIDDLEWARE
# ==============================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==============================
# URLS
# ==============================

ROOT_URLCONF = 'config.urls'


# ==============================
# TEMPLATES
# ==============================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ==============================
# WSGI
# ==============================

WSGI_APPLICATION = 'config.wsgi.application'


# ==============================
# BASE DE DATOS
# ==============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==============================
# VALIDADORES DE CONTRASEÑA
# ==============================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================
# INTERNACIONALIZACIÓN
# ==============================

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==============================
# ARCHIVOS ESTÁTICOS
# ==============================

STATIC_URL = 'static/'


# ==============================
# LOGIN / LOGOUT
# ==============================

LOGIN_URL = '/'

LOGIN_REDIRECT_URL = '/users/cliente/'

LOGOUT_REDIRECT_URL = '/'